version: "3.7"

services:
    database:
        image: mysql:8.0
        container_name: todo-database-server
        environment:
            MYSQL_ROOT_PASSWORD: sd@9sdkAil
            MYSQL_DATABASE: todo_db
            MYSQL_USER: chandra
            MYSQL_PASSWORD: Chandra@123
        networks:
            - todo_app_network
    myapp:
        build: .
        restart: always
        depends_on:
            - database
        ports:
            - "80:80"
        networks:
            - todo_app_network
        volumes:
            - .:/app
        depends_on:
            - database

networks:
    todo_app_network:
        driver: bridge