version: "3.7"

services:
    database:
        image: mysql:8.0
        container_name: todo-database-server
        environment:
            MYSQL_ROOT_PASSWORD: sd@9sdkAil
            MYSQL_DATABASE: todo_db
            MYSQL_USER: chandra
            MYSQL_PASSWORD: Chandra@123
        ports:
          - 3306:3306
        networks:
            - todo_app_network
        healthcheck:
          test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
          timeout: 20s
          retries: 10
    api:
        build: .
        restart: always
        container_name: todolist-api
        depends_on:
          database:
            condition: service_healthy
        ports:
            - "80:80"
        networks:
            - todo_app_network
        volumes:
            - .:/app
        environment:
            MYSQL_DATABASE_HOST: todo-database-server
            MYSQL_DATABASE_USER: chandra
            MYSQL_DATABASE_PASSWORD: Chandra@123
            MYSQL_DATABASE_DB: todo_db
            MYSQL_DATABASE_PORT: 3306


    webapp:
        image: nginx
        container_name: todolist-webapp
        networks:
            - todo_app_network
        ports:
            - "9876:80"
        volumes:
            - .:/usr/share/nginx/html/
        depends_on:
            - api

networks:
    todo_app_network:
        driver: bridge

